apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsu-demo-devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsu-demo-devops
  template:
    metadata:
      labels:
        app: devsu-demo-devops
    spec:
      containers:
      - name: devsu-demo-devops
        image: gcr.io/devsu-demo-devops/devsu-demo-devops:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"